#!/bin/bash -e

echo "Configuring hosts..."
for node in ts{1..4}; do
  echo "$node: uploading configuration"
  scp ./resource/config-k8s-host $node:
  echo "$node: Base configuring"
  ssh $node "sudo node=$node ./config-k8s-host" &
  PID[$node]=$!
done

wait ${PID[*]}
unset PID
echo "Base configured all hosts"

echo "Setting up master"
ssh ts1 'sudo kubeadm init --apiserver-cert-extra-sans=ts1.maas --pod-network-cidr=192.168.0.0/16'
ssh ts1 'mkdir -p $HOME/.kube'
ssh ts1 'sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config'
ssh ts1 'sudo chown $(id -u):$(id -g) $HOME/.kube/config'
scp ./resource/calico.yaml ts1:
echo "Configuring CNI"

ssh ts1 'kubectl apply -f $HOME/calico.yaml'
JOIN=$(ssh -o StrictHostKeyChecking=no ts1 \
    "sudo kubeadm token create --print-join-command")

echo "Setting up workers"
for node in ts{2..4}; do
  echo "$node: joining as worker"
  ssh -o StrictHostKeyChecking=no $node "sudo $JOIN"
  PID[$node]=$!
done
wait ${PID[*]}

echo "done"
